version: "3.9"
services:
  headlesscore:
    build:
      args:
       - HOSTUSERID=${HOSTUSERID:-1000}
       - HOSTGROUPID=${HOSTGROUPID:-1000}
    tty: true
    stdin_open: true
    environment:
      - STEAMBETA=${STEAMBETA}
      - STEAMLOGIN=${STEAMLOGIN}
      - CLEANASSETS=${CLEANASSETS:-true}
      - CLEANLOGS=${CLEANLOGS:-true}
    volumes:
      - "./Config:/Config"
      - "./Logs:/Logs"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
